# ... 前面内容不变 ...

# 设置环境变量
ENV PYTHONUNBUFFERED=1 \
    MAX_WORKERS=10 \
    TIMEOUT=10 \
    FFMPEG_ENABLE=true \
    ENABLE_RETRY=true \
    ENABLE_IP_RESOLVE=true \
    ENABLE_REGION_FILTER=false \
    PREFERRED_LOCATION="" \
    PREFERRED_ISP="" \
    CACHE_SPEED_HOURS=24 \
    CACHE_RAW_HOURS=24 \
    MAX_SOURCES_PER_CHANNEL=5 \
    DEMO_MATCH_MODE=contains \
    ENABLE_DEMO_FILTER=true \
    ENABLE_ALIAS=true \
    ENABLE_BLACKLIST=true \
    DATABASE_ENABLE=true \
    RUN_MODE=schedule \
    SCHEDULE_INTERVAL=21600

# 暴露 Web 服务端口
EXPOSE 8080

ENTRYPOINT ["./entrypoint.sh"]
